//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBankModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients:IBankClient
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public int Balance { get; set; }
        public int Deposit { get; set; }
        public double Tax { get; set; }
        public bool Vip { get; set; }
        public int DepositBonus { get; set; }
        public string Comment { get; set; }

        public Clients() { }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="n">имя </param>
        /// <param name="ln">фамилия</param>
        /// <param name="d">депозит</param>
        /// <param name="t">проуент на депозит</param>
        /// <param name="v">вип</param>
        /// <param name="db">деп бонус</param>
        /// <param name="co">комент</param>
        public Clients(string n, string ln, int d, double t, bool v, int db, string co )
        {
            Name = n;
            LastName = ln;
            Deposit = d;
            Balance = d;
            Tax = t;
            Vip = v;
            DepositBonus = db;
            Comment = co;
        }
    }
}
