//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBankModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credits:IBankCredit
    {
        public int Id { get; set; }
        public int Sum { get; set; }
        public System.DateTime Date { get; set; }
        public int Loan { get; set; }
        public string Target { get; set; }
        public int VipBonus { get; set; }
        public int ClientId { get; set; }

        public Credits() { }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="s">сумма</param>
        /// <param name="l">поцент</param>
        /// <param name="t">цель</param>
        /// <param name="vb">вип бонус</param>
        /// <param name="cid">клиент id</param>
        public Credits(int s, int l, string t, int vb, int cid)
        {
            Sum = s;
            Date = DateTime.Now;
            Loan = l;
            Target = t;
            VipBonus = vb;
            ClientId = cid;
        }
    }
}
