//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBankModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lizings:IBankCredit
    {
        public int Id { get; set; }
        public int Sum { get; set; }
        public System.DateTime Date { get; set; }
        public int Loan { get; set; }
        public string Target { get; set; }
        public int ComeBack { get; set; }
        public int FirmId { get; set; }

        public Lizings() { }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="sum"> сумма</param>
        /// <param name="loan">процент</param>
        /// <param name="targ">цель</param>
        /// <param name="cb">возврат</param>
        /// <param name="fid">ид фирмы</param>
        public Lizings(int sum, int loan, string targ, int cb, int fid)
        {
            Sum = sum;
            Date = DateTime.Now;
            Loan = loan;
            Target = targ;
            ComeBack = cb;
            FirmId = fid;
        }
    }
}
